const TestDefaultValues = {
  maddash_url: 'https://pmp-central.geant.org/maddash-webui/',
  apiurl_nodes: 'https://localhost/api/nodes',
  apiurl_run: 'https://localhost/api/runm',
  apiurl_firstrunhref: 'https://localhost/api/getfirstrun',
  apiurl_resultshref: 'https://localhost/api/getresults',
  apiurl_testshref: 'https://localhost/api/gettests',
  devapiurl_nodes: 'http://localhost/api/nodes',
  devapiurl_run: 'http://localhost/api/runm',
  devapiurl_firstrunhref: 'http://localhost/api/getfirstrun',
  devapiurl_resultshref: 'http://localhost/api/getresults',
  devapiurl_testshref: 'http://localhost/api/gettests',
  geant_nodes:{
    rows:[
      {"label":"GN - Lisbon BW - psmp-gn-bw-lis-pt.geant.org", "value":"psmp-gn-bw-lis-pt.geant.org"},
      {"label":"GN - Lisbon OWD - psmp-gn-owd-lis-pt.geant.org", "value":"psmp-gn-owd-lis-pt.geant.org"},
      {"label":"GN - Poznan BW - psmp-gn-bw-poz-pl.geant.org", "value":"psmp-gn-bw-poz-pl.geant.org"},
      {"label":"GN - Poznan OWD - psmp-gn-owd-poz-pl.geant.org", "value":"psmp-gn-owd-poz-pl.geant.org"},
      {"label":"GN - London BW - psmp-gn-bw-lon2-uk.geant.org", "value":"psmp-gn-bw-lon2-uk.geant.org"},
      {"label":"GN - London OWD - psmp-gn-owd-lon2-uk.geant.org", "value":"psmp-gn-owd-lon2-uk.geant.org"},
      {"label":"GN - Budapest BW - psmp-gn-bw-bud-hu.geant.org", "value":"psmp-gn-bw-bud-hu.geant.org"},
      {"label":"GN - Budapest OWD - psmp-gn-owd-bud-hu.geant.org", "value":"psmp-gn-owd-bud-hu.geant.org"},
      {"label":"GN - Vienna BW - psmp-gn-bw-vie-at.geant.org", "value":"psmp-gn-bw-vie-at.geant.org"},
      {"label":"GN - Vienna OWD - psmp-gn-owd-vie-at.geant.org", "value":"psmp-gn-owd-vie-at.geant.org"},
      {"label":"ESNET TP - albq-ps-tp.es.net", "value":"albq-ps-tp.es.net"},
      {"label":"ESNET LAT - albq-ps-lat.es.net", "value":"albq-ps-lat.es.net"},
      {"label":"ESNET TP - atla-ps-tp.es.net", "value":"atla-ps-tp.es.net"},
      {"label":"ESNET LAT - atla-ps-lat.es.net", "value":"atla-ps-lat.es.net"},
      {"label":"ESNET TP - bois-ps-tp.es.net", "value":"bois-ps-tp.es.net"},
      {"label":"ESNET LAT - bois-ps-lat.es.net", "value":"bois-ps-lat.es.net"},
    ]
  },
  tests: [
    'throughput',
    'latency',
    'rtt',
    'trace'
  ],
  defaultparams: {
    general: {
      default_test: 'trace',
      default_ipversion: '4',
    },
    latency: {
      packet_count: 100,
      packet_count_min: 10,
      packet_count_max: 1000000,
      packet_interval: 0.1,
      packet_interval_min: 0.000001,
      packet_interval_max: 1,
      packet_timeout: 2,
      packet_timeout_min: 1,
      packet_timeout_max: 10,
      packet_padding: 20,
      packet_padding_min: 14,
      packet_padding_max: 20000,
    },
    rtt: {
      packets_per_test: 5,
      packets_per_test_min: 1,
      packets_per_test_max: 100,
      time_between_packets: 1,
      time_between_packets_min: 1,
      time_between_packets_max: 100,
      packet_size: 1000,
      packet_size_min: 1,
      packet_size_max: 20000,
    },
    throughput: {
      protocol: 'TCP',
      test_duration: 10,
      test_duration_min: 1,
      test_duration_max: 1000,
      test_duration_units: 'S',
      tool: 'iperf3,iperf',
      autotuning: false,
      parallelstreams: 1,
      parallelstreams_min: 1,
      parallelstreams_max: 64,
      omitinterval: 0,
      omitinterval_min: 0,
      omitinterval_max: 100,
      zerocopy: false,
      tos_bits: 0,
      tos_bits_min: 0,
      tos_bits_max: 511,
      window_size: '',
      window_size_min: '0',
      window_size_max: '1GB',
    },
    trace: {
      tool: 'traceroute,tracepath',
      packet_size: 1000,
      packet_size_min: 1,
      packet_size_max: 20000,
      first_ttl: 1,
      max_ttl: 30,
      max_ttl_min: 1,
      max_ttl_max: 100,
    }
  }
}

export default TestDefaultValues;
