version: "3.3"

services:
  psgui:
    build: .
    volumes:
      - ./custom_TestDefaultValues.js:/psgui/src/includes/TestDefaultValues.js
      - ./custom_config.py:/psproxy/config.py
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx.key:/etc/nginx/ssl/nginx.key
      - ./.htpasswd:/etc/nginx/.htpasswd
    stdin_open: true
    ports:
      - 443:443
