const TestDefaultValues = {
  apiurl_nodes: 'http://psgui.qalab.geant.org/api/nodes',
  apiurl_run: 'http://psgui.qalab.geant.org/api/runm',
  apiurl_firstrunhref: 'http://psgui.qalab.geant.org/api/getfirstrun',
  apiurl_resultshref: 'http://psgui.qalab.geant.org/api/getresults',
  devapiurl_nodes: 'http://127.0.0.1:5000/api/nodes',
  devapiurl_run: 'http://127.0.0.1:5000/api/runm',
  devapiurl_firstrunhref: 'http://127.0.0.1:5000/api/getfirstrun',
  devapiurl_resultshref: 'http://127.0.0.1:5000/api/getresults',
  geant_nodes:{
    rows:[
      {"label":"GÉANT- Lisbon BW IPv4 - psmp-gn-bw-01-lis-pt-v4.geant.net", "value":"psmp-gn-bw-01-lis-pt-v4.geant.net"},
      {"label":"GÉANT- Lisbon BW IPv6 - psmp-gn-bw-01-lis-pt-v6.geant.net", "value":"psmp-gn-bw-01-lis-pt-v6.geant.net"},
      {"label":"GÉANT- Poznan BW IPv4 - psmp-gn-bw-01-poz-pl-v4.geant.net", "value":"psmp-gn-bw-01-poz-pl-v4.geant.net"},
      {"label":"GÉANT- Poznan BW IPv6 - psmp-gn-bw-01-poz-pl-v6.geant.net", "value":"psmp-gn-bw-01-poz-pl-v6.geant.net"},
      {"label":"GÉANT- Geneva BW - psmp-gn-bw-gen-ch.geant.org", "value":"psmp-gn-bw-gen-ch.geant.org"},
      {"label":"GÉANT- London BW - psmp-gn-bw-lon-uk.geant.org", "value":"psmp-gn-bw-lon-uk.geant.org"},
      {"label":"GÉANT- Sofia BW - psmp-gn-bw-sof-bg.geant.org", "value":"psmp-gn-bw-sof-bg.geant.org"},
      {"label":"GÉANT- Lisbon OWD IPv4 - psmp-gn-owd-01-lis-pt-v4.geant.net", "value":"psmp-gn-owd-01-lis-pt-v4.geant.net"},
      {"label":"GÉANT- Lisbon OWD IPv6 - psmp-gn-owd-01-lis-pt-v6.geant.net", "value":"psmp-gn-owd-01-lis-pt-v6.geant.net"},
      {"label":"GÉANT- Poznan OWD IPv4 - psmp-gn-owd-01-poz-pl-v4.geant.net", "value":"psmp-gn-owd-01-poz-pl-v4.geant.net"},
      {"label":"GÉANT- Poznan OWD IPv6 - psmp-gn-owd-01-poz-pl-v6.geant.net", "value":"psmp-gn-owd-01-poz-pl-v6.geant.net"},
      {"label":"GÉANT- Geneva OWD - psmp-gn-owd-gen-ch.geant.org", "value":"psmp-gn-owd-gen-ch.geant.org"},
      {"label":"GÉANT- London OWD - psmp-gn-owd-lon-uk.geant.org", "value":"psmp-gn-owd-lon-uk.geant.org"},
      {"label":"GÉANT- Sofia OWD - psmp-gn-owd-sof-bg.geant.org", "value":"psmp-gn-owd-sof-bg.geant.org"}
    ]
  },
  tests: [
    'throughput',
    'latency',
    'rtt',
    'trace'
  ],
  defaultparams: {
    general: {
      default_test: 'trace',
      default_ipversion: '4',
    },
    latency: {
      packet_count: 100,
      packet_count_min: 10,
      packet_count_max: 1000000,
      packet_interval: 0.1,
      packet_interval_min: 0.000001,
      packet_interval_max: 1,
      packet_timeout: 2,
      packet_timeout_min: 1,
      packet_timeout_max: 10,
      packet_padding: 20,
      packet_padding_min: 14,
      packet_padding_max: 20000,
    },
    rtt: {
      packets_per_test: 5,
      packets_per_test_min: 1,
      packets_per_test_max: 100,
      time_between_packets: 1,
      time_between_packets_min: 1,
      time_between_packets_max: 100,
      packet_size: 1000,
      packet_size_min: 1,
      packet_size_max: 20000,
    },
    throughput: {
      protocol: 'TCP',
      test_duration: 10,
      test_duration_min: 1,
      test_duration_max: 1000,
      test_duration_units: 'S',
      tool: 'iperf3,iperf',
      autotuning: false,
      parallelstreams: 1,
      parallelstreams_min: 1,
      parallelstreams_max: 64,
      omitinterval: 0,
      omitinterval_min: 0,
      omitinterval_max: 100,
      zerocopy: false,
      tos_bits: 0,
      tos_bits_min: 0,
      tos_bits_max: 511,
      window_size: '',
      window_size_min: '0',
      window_size_max: '1GB',
    },
    trace: {
      tool: 'traceroute,tracepath',
      packet_size: 1000,
      packet_size_min: 1,
      packet_size_max: 20000,
      first_ttl: 1,
      max_ttl: 30,
      max_ttl_min: 1,
      max_ttl_max: 100,
    }
  }
}

export default TestDefaultValues;