version: "3.3"

services:
  psproxy:
    build: psproxy
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./psproxy:/psproxy
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"

  psgui:
    build: psgui
    environment:
      NODE_ENV: development
    volumes:
      # mount current dir into docker container
      - ./psgui:/psgui
      # ignore local node_modules, use container
      - /psgui/node_modules
    stdin_open: true
    ports:
      - "3000:3000"
